### ISSUE TITLE
Profile exceptions cause bot to crash

### ISSUE THREAD

**Issue by zzi-zzi-zzi** [BosslandGmbH/SenseibuddyBugs#3]
Currently if a profile tag throws an exception the bot will keep re-trying that tag causing the bot to crash (flood of exception messages)

**Comment by ApocDev** [comment]
This is actually intended behavior. Profile tags should be catching any exceptions and handling them correctly.

Designed this way because sometimes the game state, and bot state, don't entirely agree. So we throw a memory exception (for instance when an object goes invalid), and restart the logic tick over again using a new game state.

This has drawbacks as you have noticed, but those are the bugs you should be reporting. (Which tags cause the exception loops, etc)
